### ISSUE TITLE
Swift 3 conversion

### ISSUE THREAD

**Issue by EynErgy** [Szaq/BinarySwift#1]
Hi,

Would you mind looking to adapt this nice piece of work to Swift 3.

I have an issue with the 'unsafeConversion' function of Common.swift

Regards,
Eyn

**Comment by EynErgy** [comment]
Hi,
I made the necessary changes on the version I forked.
Firsts tests are ok

**Comment by Szaq** [comment]
I am so sorry, I missed notification email. PR if still interested :)

**Comment by EynErgy** [comment]
Sorry I did not saw your answer.
But version 9.4.0 is great, thanks

And now with swift 4.0 there is a new set of issues.
Most critical is an issue with the Integer extensions for UINT32 and UINT64.

Could you please have a look?
I will also look on my side and if I found out I will post

**Comment by Szaq** [comment]
Thanks for the feedback. Will look into this issue.

**Comment by Szaq** [comment]
@EynErgy What kind of errors are those? I've migrated project to Swift 4. Fixed one place with complex statement and I don't get any more errors.

**Comment by EynErgy** [comment]
Hello, not yet synchro on cocoapods but I tried manually and it seems to solve everything.
thanks a lot

**Comment by Szaq** [comment]
I've published 0.9.5 to cocoapods. Thanks for your feedback :)
