### ISSUE TITLE
Consider Providing a Swift Package

### ISSUE THREAD

**Issue by CuriousTommy** [Szaq/BinarySwift#4]
Hello,

I was wondering if you would be able to also provide a Swift Package. I would [do it myself](https://developer.apple.com/documentation/xcode/creating_a_swift_package_with_xcode), but I not sure how to do this without breaking your current setup.

My main motivation is to make it easy to import this package on Linux.

**Comment by Szaq** [comment]
That's good idea. I am a bit low on time, but I will see if I will find time in next couple of weeks. If you want to give it a try, then I'll be more than happy to merge your PR.

**Comment by CuriousTommy** [comment]
I think I may have an idea on how to implement this (hopefully without breaking the other stuff). I'll work on it when I get some free time.

**Comment by Szaq** [comment]
PR merged
