### ISSUE TITLE
Writer?

### ISSUE THREAD

**Issue by andrews05** [Szaq/BinarySwift#6]
Thanks heaps for this great package. I need to both read and write data, do you have any plans to add a binary writer?

**Comment by Szaq** [comment]
That sounds like a great idea, but to be honest I don't have much time now. I'd be happy to accept PR though:)

**Comment by andrews05** [comment]
So I was going to work on this but I discovered that writing data is actually easier than I thought and I don't really need a dedicated writer class. Thanks anyway though.
